### ISSUE TITLE
Set up a database that we can store "claps" in

### ISSUE THREAD

**Issue by Vinnl** [Vinnl/jic-jac#1]

**Comment by Ilozuluchris** [comment]
Hello @Vinnl could you give more info about this? What kind of database to be used?  etc

**Comment by Vinnl** [comment]
Hi @Ilozuluchris, sorry for the unclarity - we're part of the [eLife Innovation Sprint](https://elifesciences.org/events/c40798c3/elife-innovation-sprint-2018) and hence are working on this with a few people in-person, and we're struggling a bit involving virtual participants. In this case, we're prototyping an embeddable widget for preprint servers and the likes to embed, and we're doing so using Glitch: https://glitch.com/edit/#!/jic-jacs For the prototyping, we were thinking about simply embedding an SQLite database on there ([example](https://glitch.com/~hello-sqlite)) - which I thought was already setup, but I can't see it right now. The person who was doing that hasn't confirmed their membership of this project yet, which is why they're not assigned. It's almost dinner time here now, so there's probably not going to be that much activity in the coming hours (and perhaps not until tomorrow morning).

The upside is that if you're looking for something to do, you can be sure no one will interfere with it :) You could look at forking that Glitch project and see if you can add a working database (SQLite or otherwise), and an endpoint that writes data to it?
