### ISSUE TITLE
Nail the nomenclature

### ISSUE THREAD

**Issue by afandian** [Vinnl/jic-jac#7]
Decide the vocabulary of clapping

 - fist-pump
 - clap

Future options:

 - novelty
 - clarity
 - robustness 
 - excitement

**Comment by Vinnl** [comment]
![image](https://user-images.githubusercontent.com/4251/39915132-04c2c576-54ff-11e8-9b95-549e99bfc7fd.png)

**Comment by Marknpatterson** [comment]
we've settled on the name Plaudit and registered the domain plaudit.pub
three categories to start with
clear
robust
exciting
